// Code generated by apigen schema model emitter. DO NOT EDIT.
package api

type GenSchemaCreateTodoRequest = CreateTodoRequest

type GenSchemaListTodosResponse = ListTodosResponse

type GenSchemaTodo = Todo
