// Package requestmodelgo emits APIGen-owned schema aliases from IR roots.
package requestmodelgo

import (
	"sort"
	"strings"

	"github.com/Yacobolo/toolbelt/apigen/ir"
)

// Options configures Go schema emission.
type Options struct {
	PackageName string
}

// Emit renders APIGen-owned schema aliases derived from IR roots.
func Emit(doc ir.Document, opts Options) ([]byte, error) {
	return emitAliasModels(doc, opts)
}

// EmitWithResponseRoots renders APIGen-owned request and safe response schema
// aliases using IR-declared response schemas.
func EmitWithResponseRoots(doc ir.Document, opts Options) ([]byte, error) {
	return emitAliasModels(doc, opts)
}

// EmitStandaloneCompatibilityTypes renders APIGen-owned concrete schema types
// for canonical names plus the GenSchema aliases used by generated transport.
func EmitStandaloneCompatibilityTypes(doc ir.Document, opts Options) ([]byte, error) {
	return emitStandaloneModels(doc, opts)
}

func emitAliasModels(doc ir.Document, opts Options) ([]byte, error) {
	rootNames, err := schemaRoots(doc)
	if err != nil {
		return nil, err
	}
	allNames := collectSchemaAliasSet(doc, rootNames)

	var b strings.Builder
	b.WriteString("// Code generated by apigen schema model emitter. DO NOT EDIT.\n")
	b.WriteString("package ")
	b.WriteString(packageName(opts))
	b.WriteString("\n\n")

	for _, rootName := range allNames {
		if emitAPIGenOwnedSchemaType(&b, doc, rootName) {
			continue
		}
		b.WriteString("type ")
		b.WriteString(genSchemaTypeName(rootName))
		b.WriteString(" = ")
		b.WriteString(exportedName(rootName))
		b.WriteString("\n\n")
	}

	return []byte(b.String()), nil
}

func emitStandaloneModels(doc ir.Document, opts Options) ([]byte, error) {
	allNames := standaloneCompatibilitySchemaNames(doc)
	bareEnumNames := uniqueBareEnumConstantNames(doc)

	var b strings.Builder
	b.WriteString("// Code generated by apigen standalone schema model emitter. DO NOT EDIT.\n")
	b.WriteString("package ")
	b.WriteString(packageName(opts))
	b.WriteString("\n\n")

	for _, rootName := range allNames {
		if err := emitStandaloneSchemaType(&b, doc, rootName, bareEnumNames); err != nil {
			return nil, err
		}
	}
	emitManualCompatibilityPlaceholderTypes(&b, doc)

	emitLegacyParamsAliases(&b, doc)
	emitLegacyRequestBodyAliases(&b, doc)

	return []byte(b.String()), nil
}

func packageName(opts Options) string {
	if strings.TrimSpace(opts.PackageName) == "" {
		return "api"
	}
	return opts.PackageName
}

func emitManualCompatibilityPlaceholderTypes(b *strings.Builder, doc ir.Document) {
	if _, ok := doc.Schemas["GenericRequest"]; !ok {
		b.WriteString("type GenericRequest struct {\n")
		b.WriteString("\tPayload *map[string]string `json:\"payload,omitempty\"`\n")
		b.WriteString("}\n\n")
	}
	if _, ok := doc.Schemas["GenericResponse"]; !ok {
		b.WriteString("type GenericResponse struct {\n")
		b.WriteString("\tData *map[string]string `json:\"data,omitempty\"`\n")
		b.WriteString("}\n\n")
	}
}

func standaloneCompatibilitySchemaNames(doc ir.Document) []string {
	rootNames := make([]string, 0, len(doc.Schemas))
	for name := range doc.Schemas {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return collectSchemaAliasSet(doc, rootNames)
}

func emitStandaloneSchemaType(b *strings.Builder, doc ir.Document, rootName string, bareEnumNames map[string]bool) error {
	if rootName == "Record" {
		b.WriteString("type Record map[string]any\n\n")
		return nil
	}

	schema, ok := doc.Schemas[rootName]
	if !ok {
		return nil
	}

	typeName := exportedName(rootName)
	switch schema.Type {
	case "object", "":
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" struct {\n")

		propertyNames := make([]string, 0, len(schema.Properties))
		for name := range schema.Properties {
			propertyNames = append(propertyNames, name)
		}
		sort.Strings(propertyNames)

		required := make(map[string]struct{}, len(schema.Required))
		for _, name := range schema.Required {
			required[name] = struct{}{}
		}

		for _, name := range propertyNames {
			property := schema.Properties[name]
			fieldType := standaloneSchemaRefGoType(property.Schema)
			if _, ok := required[name]; !ok {
				fieldType = "*" + fieldType
			}
			b.WriteString("\t")
			b.WriteString(exportedName(name))
			b.WriteString(" ")
			b.WriteString(fieldType)
			b.WriteString(" `json:\"")
			b.WriteString(name)
			if _, ok := required[name]; !ok {
				b.WriteString(",omitempty")
			}
			b.WriteString("\"`\n")
		}
		b.WriteString("}\n\n")
		return nil
	case "array":
		elemType := "any"
		if schema.Items != nil {
			elemType = standaloneSchemaRefGoType(*schema.Items)
		}
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" []")
		b.WriteString(elemType)
		b.WriteString("\n\n")
		return nil
	default:
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" ")
		b.WriteString(standaloneSchemaGoType(schema))
		b.WriteString("\n\n")
		emitStandaloneEnumConstants(b, typeName, schema, bareEnumNames)
		return nil
	}
}

func emitStandaloneEnumConstants(b *strings.Builder, typeName string, schema ir.Schema, bareEnumNames map[string]bool) {
	if len(schema.Enum) == 0 {
		return
	}

	b.WriteString("const (\n")
	for _, value := range schema.Enum {
		constName := typeName + exportedName(value)
		b.WriteString("\t")
		b.WriteString(constName)
		b.WriteString(" ")
		b.WriteString(typeName)
		b.WriteString(" = ")
		b.WriteString(quotedGoString(value))
		b.WriteString("\n")
		if shouldEmitBareEnumConstant(value, bareEnumNames) {
			b.WriteString("\t")
			b.WriteString(exportedName(value))
			b.WriteString(" ")
			b.WriteString(typeName)
			b.WriteString(" = ")
			b.WriteString(quotedGoString(value))
			b.WriteString("\n")
		}
	}
	b.WriteString(")\n\n")
}

func emitAPIGenOwnedSchemaType(b *strings.Builder, doc ir.Document, rootName string) bool {
	if rootName == "Record" {
		b.WriteString("type GenSchemaRecord map[string]any\n\n")
		return true
	}

	if !apigenOwnedSchemaNames[rootName] {
		return false
	}

	schema, ok := doc.Schemas[rootName]
	if !ok || schema.Type != "object" {
		return false
	}

	b.WriteString("type ")
	b.WriteString(genSchemaTypeName(rootName))
	b.WriteString(" struct {\n")

	propertyNames := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		propertyNames = append(propertyNames, name)
	}
	sort.Strings(propertyNames)

	required := make(map[string]struct{}, len(schema.Required))
	for _, name := range schema.Required {
		required[name] = struct{}{}
	}

	for _, name := range propertyNames {
		property := schema.Properties[name]
		fieldType := schemaRefGoType(property.Schema)
		if fieldType == "" {
			fieldType = "any"
		}
		if _, ok := required[name]; !ok {
			fieldType = "*" + fieldType
		}
		b.WriteString("\t")
		b.WriteString(exportedName(name))
		b.WriteString(" ")
		b.WriteString(fieldType)
		b.WriteString(" `json:\"")
		b.WriteString(name)
		if _, ok := required[name]; !ok {
			b.WriteString(",omitempty")
		}
		b.WriteString("\"`\n")
	}

	b.WriteString("}\n\n")
	return true
}

var apigenOwnedSchemaNames = map[string]bool{
	"GenericResponse": true,
	"HealthResponse":  true,
	"QueryResponse":   true,
}

func schemaRefGoType(ref ir.SchemaRef) string {
	if ref.Ref != "" {
		name, ok := normalizedSchemaRefName(ref)
		if !ok {
			return ""
		}
		return genSchemaTypeName(name)
	}

	switch ref.Type {
	case "boolean":
		return "bool"
	case "integer", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "number":
		return "float64"
	case "array":
		if ref.Items != nil {
			return "[]" + schemaRefGoType(*ref.Items)
		}
		return "[]any"
	case "object":
		return "map[string]any"
	case "string":
		return "string"
	default:
		return ""
	}
}

func standaloneSchemaRefGoType(ref ir.SchemaRef) string {
	if ref.Ref != "" {
		name, ok := normalizedSchemaRefName(ref)
		if !ok {
			return "any"
		}
		return exportedName(name)
	}

	switch ref.Type {
	case "boolean":
		return "bool"
	case "integer", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "number":
		return "float64"
	case "array":
		if ref.Items != nil {
			return "[]" + standaloneSchemaRefGoType(*ref.Items)
		}
		return "[]any"
	case "object":
		return "map[string]any"
	case "string":
		return "string"
	default:
		return "any"
	}
}

func standaloneSchemaGoType(schema ir.Schema) string {
	switch schema.Type {
	case "boolean":
		return "bool"
	case "integer", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "number":
		return "float64"
	case "string":
		return "string"
	default:
		return "any"
	}
}

func uniqueBareEnumConstantNames(doc ir.Document) map[string]bool {
	counts := make(map[string]int)
	for _, schema := range doc.Schemas {
		for _, value := range schema.Enum {
			if !isLegacyBareEnumValue(value) {
				continue
			}
			counts[exportedName(value)]++
		}
	}

	unique := make(map[string]bool, len(counts))
	for name, count := range counts {
		if count == 1 {
			unique[name] = true
		}
	}
	return unique
}

func shouldEmitBareEnumConstant(value string, bareEnumNames map[string]bool) bool {
	name := exportedName(value)
	return isLegacyBareEnumValue(value) && bareEnumNames[name]
}

func isLegacyBareEnumValue(value string) bool {
	value = strings.TrimSpace(value)
	if value == "" {
		return false
	}
	for _, r := range value {
		switch {
		case r >= 'A' && r <= 'Z':
		case r >= '0' && r <= '9':
		case r == '_':
		default:
			return false
		}
	}
	return true
}

func quotedGoString(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `\"`) + `"`
}

func collectSchemaAliasSet(doc ir.Document, rootNames []string) []string {
	seen := make(map[string]struct{}, len(rootNames))
	queue := append([]string(nil), rootNames...)

	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		schema, ok := doc.Schemas[name]
		if !ok {
			continue
		}
		for _, dep := range schemaDependencies(schema) {
			if _, ok := seen[dep]; !ok {
				queue = append(queue, dep)
			}
		}
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func schemaDependencies(schema ir.Schema) []string {
	seen := make(map[string]struct{})
	for _, property := range schema.Properties {
		collectSchemaRefDependency(property.Schema, seen)
	}
	if schema.Items != nil {
		collectSchemaRefDependency(*schema.Items, seen)
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func collectSchemaRefDependency(ref ir.SchemaRef, seen map[string]struct{}) {
	name, ok := normalizedSchemaRefName(ref)
	if !ok || name == "Error" {
		if ref.Items != nil {
			collectSchemaRefDependency(*ref.Items, seen)
		}
		return
	}
	seen[name] = struct{}{}
	if ref.Items != nil {
		collectSchemaRefDependency(*ref.Items, seen)
	}
}

func schemaRoots(doc ir.Document) ([]string, error) {
	seen := make(map[string]struct{})
	for _, name := range requestSchemaRoots(doc) {
		seen[name] = struct{}{}
	}

	for _, name := range safeResponseSchemaRoots(doc) {
		seen[name] = struct{}{}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames, nil
}

func requestSchemaRoots(doc ir.Document) []string {
	seen := make(map[string]struct{})
	for _, endpoint := range doc.Endpoints {
		if endpoint.RequestBody == nil {
			continue
		}
		if schemaName, ok := resolveRequestSchemaName(doc, endpoint); ok {
			seen[schemaName] = struct{}{}
		}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames
}

func safeResponseSchemaRoots(doc ir.Document) []string {
	seen := make(map[string]struct{})
	for _, endpoint := range doc.Endpoints {
		for _, response := range endpoint.Responses {
			if shape, ok, err := ir.ResponseShapeMetadata(response); err == nil && ok {
				if shape.BodyType != "" {
					seen[shape.BodyType] = struct{}{}
				}
			}
			if response.Schema == nil || isErrorSchemaRef(*response.Schema) {
				continue
			}
			bodyTypeName, ok := normalizedSchemaRefName(*response.Schema)
			if !ok {
				continue
			}
			seen[bodyTypeName] = struct{}{}
		}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames
}

func normalizedSchemaRefName(schema ir.SchemaRef) (string, bool) {
	return ir.NormalizedSchemaRefName(schema)
}

func isErrorSchemaRef(schema ir.SchemaRef) bool {
	ref, ok := normalizedSchemaRefName(schema)
	if !ok {
		return false
	}
	return exportedName(ref) == "Error"
}

func resolveRequestSchemaName(doc ir.Document, endpoint ir.Endpoint) (string, bool) {
	if endpoint.RequestBody == nil {
		return "", false
	}

	schema := endpoint.RequestBody.Schema
	if schema.Ref != "" && schema.Ref != "GenericRequest" {
		return normalizedSchemaRefName(schema)
	}
	if schema.Ref == "GenericRequest" {
		if schemaName, ok := ir.ResolveGenericRequestBodySchemaName(doc, endpoint.OperationID); ok {
			return schemaName, true
		}
	}
	return "", false
}

func exportedName(operationID string) string {
	parts := splitIdentifier(operationID)
	if len(parts) == 0 {
		return "Operation"
	}
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func splitIdentifier(value string) []string {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}
	replacer := strings.NewReplacer("-", " ", "_", " ", ".", " ", "/", " ")
	value = replacer.Replace(value)
	chunks := strings.Fields(value)
	if len(chunks) > 0 {
		return chunks
	}
	return []string{value}
}

func genSchemaTypeName(name string) string {
	if strings.HasPrefix(name, "GenSchema") {
		return name
	}
	if strings.TrimSpace(name) == "" {
		return "GenSchemaValue"
	}
	return "GenSchema" + exportedName(name)
}

func emitLegacyParamsAliases(b *strings.Builder, doc ir.Document) {
	names := make([]string, 0, len(doc.Endpoints))
	seen := make(map[string]struct{}, len(doc.Endpoints))
	for _, endpoint := range doc.Endpoints {
		if !endpointHasCompatibilityParams(endpoint) {
			continue
		}
		name := exportedName(endpoint.OperationID) + "Params"
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		b.WriteString("type ")
		b.WriteString(name)
		b.WriteString(" = Gen")
		b.WriteString(name)
		b.WriteString("\n\n")
	}
}

func endpointHasCompatibilityParams(endpoint ir.Endpoint) bool {
	for _, parameter := range endpoint.Parameters {
		if strings.EqualFold(parameter.In, "query") {
			return true
		}
	}
	return false
}

func emitLegacyRequestBodyAliases(b *strings.Builder, doc ir.Document) {
	aliases := compatibilityRequestBodyAliases(doc)
	names := make([]string, 0, len(aliases))
	for name := range aliases {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		b.WriteString("type ")
		b.WriteString(name)
		b.WriteString(" = ")
		b.WriteString(aliases[name])
		b.WriteString("\n\n")
	}
}

func compatibilityRequestBodyAliases(doc ir.Document) map[string]string {
	aliases := make(map[string]string)
	for _, endpoint := range doc.Endpoints {
		if endpoint.RequestBody == nil {
			continue
		}
		name := exportedName(endpoint.OperationID)
		aliases[name+"JSONRequestBody"] = "Gen" + name + "JSONBody"
	}

	for alias, schemaName := range manualCompatibilityRequestBodyAliases {
		if _, ok := doc.Schemas[schemaName]; !ok {
			continue
		}
		aliases[alias] = exportedName(schemaName)
	}

	return aliases
}

var manualCompatibilityRequestBodyAliases = map[string]string{
	"BootstrapCompleteJSONRequestBody":    "BootstrapCompleteRequest",
	"CreateBootstrapTokenJSONRequestBody": "BootstrapTokenRequest",
	"LocalLoginJSONRequestBody":           "LocalLoginRequest",
	"RevokeAllWebSessionsJSONRequestBody": "RevokeWebSessionsRequest",
	"UpsertOIDCProviderJSONRequestBody":   "OIDCProviderRequest",
}
