// Package requestmodelgo emits APIGen-owned schema aliases from IR roots.
package requestmodelgo

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Yacobolo/toolbelt/apigen/ir"
)

// Options configures Go schema emission.
type Options struct {
	PackageName string
}

// Emit renders APIGen-owned schema aliases derived from IR roots.
func Emit(doc ir.Document, opts Options) ([]byte, error) {
	return emitAliasModels(doc, opts)
}

// EmitWithResponseRoots renders APIGen-owned request and safe response schema
// aliases using IR-declared response schemas.
func EmitWithResponseRoots(doc ir.Document, opts Options) ([]byte, error) {
	return emitAliasModels(doc, opts)
}

func emitAliasModels(doc ir.Document, opts Options) ([]byte, error) {
	rootNames, err := schemaRoots(doc)
	if err != nil {
		return nil, err
	}
	aliasNames := collectSchemaAliasSet(doc, rootNames)
	concreteNames := allSchemaNames(doc)

	var b strings.Builder
	b.WriteString("// Code generated by apigen schema model emitter. DO NOT EDIT.\n")
	b.WriteString("package ")
	b.WriteString(packageName(opts))
	b.WriteString("\n\n")

	for _, rootName := range concreteNames {
		if err := emitCanonicalSchemaType(&b, doc, rootName); err != nil {
			return nil, err
		}
	}

	for _, rootName := range aliasNames {
		if emitAPIGenOwnedSchemaType(&b, doc, rootName) {
			continue
		}
		b.WriteString("type ")
		b.WriteString(genSchemaTypeName(rootName))
		b.WriteString(" = ")
		b.WriteString(exportedName(rootName))
		b.WriteString("\n\n")
	}

	return []byte(b.String()), nil
}

func packageName(opts Options) string {
	if strings.TrimSpace(opts.PackageName) == "" {
		return "api"
	}
	return opts.PackageName
}

func emitAPIGenOwnedSchemaType(b *strings.Builder, doc ir.Document, rootName string) bool {
	if rootName == "Record" {
		b.WriteString("type GenSchemaRecord map[string]any\n\n")
		return true
	}

	if !apigenOwnedSchemaNames[rootName] {
		return false
	}

	schema, ok := doc.Schemas[rootName]
	if !ok || schema.Type != "object" {
		return false
	}

	b.WriteString("type ")
	b.WriteString(genSchemaTypeName(rootName))
	b.WriteString(" struct {\n")

	propertyNames := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		propertyNames = append(propertyNames, name)
	}
	sort.Strings(propertyNames)

	required := make(map[string]struct{}, len(schema.Required))
	for _, name := range schema.Required {
		required[name] = struct{}{}
	}

	for _, name := range propertyNames {
		property := schema.Properties[name]
		fieldType := schemaRefGoType(property.Schema)
		if fieldType == "" {
			fieldType = "any"
		}
		if _, ok := required[name]; !ok {
			fieldType = "*" + fieldType
		}
		b.WriteString("\t")
		b.WriteString(exportedName(name))
		b.WriteString(" ")
		b.WriteString(fieldType)
		b.WriteString(" `json:\"")
		b.WriteString(name)
		if _, ok := required[name]; !ok {
			b.WriteString(",omitempty")
		}
		b.WriteString("\"`\n")
	}

	b.WriteString("}\n\n")
	return true
}

func allSchemaNames(doc ir.Document) []string {
	names := make([]string, 0, len(doc.Schemas))
	for name := range doc.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func emitCanonicalSchemaType(b *strings.Builder, doc ir.Document, rootName string) error {
	if rootName == "Record" {
		b.WriteString("type Record map[string]any\n\n")
		return nil
	}

	schema, ok := doc.Schemas[rootName]
	if !ok {
		return nil
	}

	typeName := exportedName(rootName)
	switch schema.Type {
	case "object", "":
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" struct {\n")

		propertyNames := make([]string, 0, len(schema.Properties))
		for name := range schema.Properties {
			propertyNames = append(propertyNames, name)
		}
		sort.Strings(propertyNames)

		required := make(map[string]struct{}, len(schema.Required))
		for _, name := range schema.Required {
			required[name] = struct{}{}
		}

		for _, name := range propertyNames {
			property := schema.Properties[name]
			fieldType := standaloneSchemaRefGoType(property.Schema)
			if _, ok := required[name]; !ok {
				fieldType = "*" + fieldType
			}
			b.WriteString("\t")
			b.WriteString(exportedName(name))
			b.WriteString(" ")
			b.WriteString(fieldType)
			b.WriteString(" `json:\"")
			b.WriteString(name)
			if _, ok := required[name]; !ok {
				b.WriteString(",omitempty")
			}
			b.WriteString("\"`\n")
		}
		b.WriteString("}\n\n")
		return nil
	case "array":
		elemType := "any"
		if schema.Items != nil {
			elemType = standaloneSchemaRefGoType(*schema.Items)
		}
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" []")
		b.WriteString(elemType)
		b.WriteString("\n\n")
		return nil
	default:
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" ")
		b.WriteString(standaloneSchemaGoType(schema))
		b.WriteString("\n\n")
		emitCanonicalEnumConstants(b, typeName, schema)
		return nil
	}
}

func emitCanonicalEnumConstants(b *strings.Builder, typeName string, schema ir.Schema) {
	if len(schema.Enum) == 0 {
		return
	}

	b.WriteString("const (\n")
	for _, value := range schema.Enum {
		constName := typeName + exportedName(value)
		b.WriteString("\t")
		b.WriteString(constName)
		b.WriteString(" ")
		b.WriteString(typeName)
		b.WriteString(" = ")
		b.WriteString(quotedGoString(value))
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

var apigenOwnedSchemaNames = map[string]bool{
	"GenericResponse": true,
	"HealthResponse":  true,
	"QueryResponse":   true,
}

func schemaRefGoType(ref ir.SchemaRef) string {
	if ref.Ref != "" {
		name, ok := normalizedSchemaRefName(ref)
		if !ok {
			return ""
		}
		return genSchemaTypeName(name)
	}

	switch ref.Type {
	case "boolean":
		return "bool"
	case "integer", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "number":
		return "float64"
	case "array":
		if ref.Items != nil {
			return "[]" + schemaRefGoType(*ref.Items)
		}
		return "[]any"
	case "object":
		return "map[string]any"
	case "string":
		return "string"
	default:
		return ""
	}
}

func standaloneSchemaRefGoType(ref ir.SchemaRef) string {
	if ref.Ref != "" {
		name, ok := normalizedSchemaRefName(ref)
		if !ok {
			return "any"
		}
		return exportedName(name)
	}

	switch ref.Type {
	case "boolean":
		return "bool"
	case "integer", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "number":
		return "float64"
	case "array":
		if ref.Items != nil {
			return "[]" + standaloneSchemaRefGoType(*ref.Items)
		}
		return "[]any"
	case "object":
		return "map[string]any"
	case "string":
		return "string"
	default:
		return "any"
	}
}

func standaloneSchemaGoType(schema ir.Schema) string {
	switch schema.Type {
	case "boolean":
		return "bool"
	case "integer", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "number":
		return "float64"
	case "string":
		return "string"
	default:
		return "any"
	}
}

func quotedGoString(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `\"`) + `"`
}

func collectSchemaAliasSet(doc ir.Document, rootNames []string) []string {
	seen := make(map[string]struct{}, len(rootNames))
	queue := append([]string(nil), rootNames...)

	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		schema, ok := doc.Schemas[name]
		if !ok {
			continue
		}
		for _, dep := range schemaDependencies(schema) {
			if _, ok := seen[dep]; !ok {
				queue = append(queue, dep)
			}
		}
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func schemaDependencies(schema ir.Schema) []string {
	seen := make(map[string]struct{})
	for _, property := range schema.Properties {
		collectSchemaRefDependency(property.Schema, seen)
	}
	if schema.Items != nil {
		collectSchemaRefDependency(*schema.Items, seen)
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func collectSchemaRefDependency(ref ir.SchemaRef, seen map[string]struct{}) {
	name, ok := normalizedSchemaRefName(ref)
	if !ok || name == "Error" {
		if ref.Items != nil {
			collectSchemaRefDependency(*ref.Items, seen)
		}
		return
	}
	seen[name] = struct{}{}
	if ref.Items != nil {
		collectSchemaRefDependency(*ref.Items, seen)
	}
}

func schemaRoots(doc ir.Document) ([]string, error) {
	seen := make(map[string]struct{})
	requestRoots, err := requestSchemaRoots(doc)
	if err != nil {
		return nil, err
	}
	for _, name := range requestRoots {
		seen[name] = struct{}{}
	}

	for _, name := range safeResponseSchemaRoots(doc) {
		seen[name] = struct{}{}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames, nil
}

func requestSchemaRoots(doc ir.Document) ([]string, error) {
	seen := make(map[string]struct{})
	for _, endpoint := range doc.Endpoints {
		if endpoint.RequestBody == nil {
			continue
		}
		if schemaName, ok := resolveRequestSchemaName(doc, endpoint); ok {
			seen[schemaName] = struct{}{}
			continue
		}
		return nil, fmt.Errorf("request body generation for %s requires a named IR schema", endpoint.OperationID)
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames, nil
}

func safeResponseSchemaRoots(doc ir.Document) []string {
	seen := make(map[string]struct{})
	for _, endpoint := range doc.Endpoints {
		for _, response := range endpoint.Responses {
			if shape, ok, err := ir.ResponseShapeMetadata(response); err == nil && ok {
				if shape.BodyType != "" {
					seen[shape.BodyType] = struct{}{}
				}
			}
			if response.Schema == nil || isErrorSchemaRef(*response.Schema) {
				continue
			}
			bodyTypeName, ok := normalizedSchemaRefName(*response.Schema)
			if !ok {
				continue
			}
			seen[bodyTypeName] = struct{}{}
		}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames
}

func normalizedSchemaRefName(schema ir.SchemaRef) (string, bool) {
	return ir.NormalizedSchemaRefName(schema)
}

func isErrorSchemaRef(schema ir.SchemaRef) bool {
	ref, ok := normalizedSchemaRefName(schema)
	if !ok {
		return false
	}
	return exportedName(ref) == "Error"
}

func resolveRequestSchemaName(doc ir.Document, endpoint ir.Endpoint) (string, bool) {
	return ir.ResolveRequestBodySchemaName(doc, endpoint)
}

func exportedName(operationID string) string {
	parts := splitIdentifier(operationID)
	if len(parts) == 0 {
		return "Operation"
	}
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func splitIdentifier(value string) []string {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}
	replacer := strings.NewReplacer("-", " ", "_", " ", ".", " ", "/", " ")
	value = replacer.Replace(value)
	chunks := strings.Fields(value)
	if len(chunks) > 0 {
		return chunks
	}
	return []string{value}
}

func genSchemaTypeName(name string) string {
	if strings.HasPrefix(name, "GenSchema") {
		return name
	}
	if strings.TrimSpace(name) == "" {
		return "GenSchemaValue"
	}
	return "GenSchema" + exportedName(name)
}
