// Package modelgo emits Go data-contract model types from APIGen IR.
package modelgo

import (
	"fmt"
	"strings"

	"github.com/Yacobolo/toolbelt/apigen/emit/contractutil"
	"github.com/Yacobolo/toolbelt/apigen/ir"
)

// Options configures Go model emission.
type Options struct {
	PackageName string
}

// Emit renders Go data-contract model types for doc.Contracts.
func Emit(doc ir.Document, opts Options) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by apigen data-contract Go emitter. DO NOT EDIT.\n")
	b.WriteString("package ")
	b.WriteString(packageName(opts))
	b.WriteString("\n\n")

	for _, name := range contractutil.DependencyNames(doc) {
		schema, ok := doc.Schemas[name]
		if !ok {
			return nil, fmt.Errorf("contract schema %q is missing", name)
		}
		emitSchema(&b, name, schema)
	}
	return []byte(b.String()), nil
}

func packageName(opts Options) string {
	if strings.TrimSpace(opts.PackageName) == "" {
		return "contracts"
	}
	return opts.PackageName
}

func emitSchema(b *strings.Builder, name string, schema ir.Schema) {
	typeName := exportedName(name)
	switch schema.Type {
	case "object", "":
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" struct {\n")
		required := contractutil.RequiredSet(schema)
		for _, propertyName := range contractutil.OrderedProperties(schema) {
			property := schema.Properties[propertyName]
			fieldType := schemaRefGoType(property.Schema)
			if _, ok := required[propertyName]; !ok {
				fieldType = "*" + fieldType
			}
			b.WriteString("\t")
			b.WriteString(exportedName(propertyName))
			b.WriteString(" ")
			b.WriteString(fieldType)
			b.WriteString(" `json:\"")
			b.WriteString(propertyName)
			if _, ok := required[propertyName]; !ok {
				b.WriteString(",omitempty")
			}
			b.WriteString("\"`\n")
		}
		b.WriteString("}\n\n")
	case "array":
		elem := "any"
		if schema.Items != nil {
			elem = schemaRefGoType(*schema.Items)
		}
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" []")
		b.WriteString(elem)
		b.WriteString("\n\n")
	default:
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" ")
		b.WriteString(schemaGoType(schema.Type, schema.Items, ""))
		b.WriteString("\n\n")
		emitEnumConstants(b, typeName, schema.Enum)
	}
}

func schemaRefGoType(ref ir.SchemaRef) string {
	if ref.Ref != "" {
		name, ok := ir.NormalizedSchemaRefName(ref)
		if ok {
			return exportedName(name)
		}
		return "any"
	}
	if ref.AdditionalProperties != nil {
		if ref.AdditionalProperties.Schema != nil {
			return "map[string]" + schemaRefGoType(*ref.AdditionalProperties.Schema)
		}
		return "map[string]any"
	}
	return schemaGoType(ref.Type, ref.Items, ref.Format)
}

func schemaGoType(schemaType string, items *ir.SchemaRef, format string) string {
	switch schemaType {
	case "boolean":
		return "bool"
	case "integer":
		if format == "int64" {
			return "int64"
		}
		return "int32"
	case "number":
		return "float64"
	case "array":
		if items != nil {
			return "[]" + schemaRefGoType(*items)
		}
		return "[]any"
	case "object":
		return "map[string]any"
	case "string":
		return "string"
	default:
		return "any"
	}
}

func emitEnumConstants(b *strings.Builder, typeName string, values []string) {
	if len(values) == 0 {
		return
	}
	b.WriteString("const (\n")
	for _, value := range values {
		b.WriteString("\t")
		b.WriteString(typeName)
		b.WriteString(exportedName(value))
		b.WriteString(" ")
		b.WriteString(typeName)
		b.WriteString(" = ")
		b.WriteString(quotedGoString(value))
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func exportedName(value string) string {
	parts := splitIdentifier(value)
	if len(parts) == 0 {
		return "Value"
	}
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func splitIdentifier(value string) []string {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}
	var words []string
	var current strings.Builder
	var prevLower bool
	for _, r := range value {
		if r == '-' || r == '_' || r == '.' || r == '/' || r == ' ' {
			if current.Len() > 0 {
				words = append(words, current.String())
				current.Reset()
			}
			prevLower = false
			continue
		}
		isUpper := 'A' <= r && r <= 'Z'
		if isUpper && prevLower && current.Len() > 0 {
			words = append(words, current.String())
			current.Reset()
		}
		current.WriteRune(r)
		prevLower = 'a' <= r && r <= 'z'
	}
	if current.Len() > 0 {
		words = append(words, current.String())
	}
	if len(words) == 0 {
		return nil
	}
	return words
}

func quotedGoString(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `\"`) + `"`
}
