// Package modelgo emits Go data-contract model types from APIGen IR.
package modelgo

import (
	"fmt"
	"strings"

	"github.com/Yacobolo/toolbelt/apigen/emit/contractutil"
	"github.com/Yacobolo/toolbelt/apigen/emit/gotype"
	"github.com/Yacobolo/toolbelt/apigen/emit/gounion"
	"github.com/Yacobolo/toolbelt/apigen/ir"
)

// Options configures Go model emission.
type Options struct {
	PackageName string
}

// Emit renders Go data-contract model types for doc.Contracts.
func Emit(doc ir.Document, opts Options) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by apigen data-contract Go emitter. DO NOT EDIT.\n")
	b.WriteString("package ")
	b.WriteString(packageName(opts))
	b.WriteString("\n\n")

	names := contractutil.DependencyNames(doc)
	if hasUnion(doc, names) {
		b.WriteString("import (\n\t\"bytes\"\n\t\"encoding/json\"\n\t\"fmt\"\n)\n\n")
	}
	for _, name := range names {
		schema, ok := doc.Schemas[name]
		if !ok {
			return nil, fmt.Errorf("contract schema %q is missing", name)
		}
		emitSchema(&b, doc, name, schema)
	}
	return []byte(b.String()), nil
}

func packageName(opts Options) string {
	if strings.TrimSpace(opts.PackageName) == "" {
		return "contracts"
	}
	return opts.PackageName
}

func emitSchema(b *strings.Builder, doc ir.Document, name string, schema ir.Schema) {
	typeName := exportedName(name)
	switch schema.Type {
	case "union":
		gounion.Emit(b, doc, name, schema, exportedName)
	case "object", "":
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" struct {\n")
		if schema.Base != nil {
			b.WriteString("\t")
			b.WriteString(schemaRefGoType(*schema.Base))
			b.WriteString("\n")
		}
		required := contractutil.RequiredSet(schema)
		for _, propertyName := range contractutil.OrderedProperties(schema) {
			property := schema.Properties[propertyName]
			fieldType := schemaRefGoType(property.Schema)
			if _, ok := required[propertyName]; !ok {
				fieldType = "*" + fieldType
			}
			b.WriteString("\t")
			b.WriteString(exportedName(propertyName))
			b.WriteString(" ")
			b.WriteString(fieldType)
			b.WriteString(" `json:\"")
			b.WriteString(propertyName)
			if _, ok := required[propertyName]; !ok {
				b.WriteString(",omitempty")
			}
			b.WriteString("\"`\n")
		}
		b.WriteString("}\n\n")
	case "array":
		elem := "any"
		if schema.Items != nil {
			elem = schemaRefGoType(*schema.Items)
		}
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" []")
		b.WriteString(elem)
		b.WriteString("\n\n")
	default:
		b.WriteString("type ")
		b.WriteString(typeName)
		b.WriteString(" ")
		b.WriteString(schemaGoType(schema.Type, schema.Items, ""))
		b.WriteString("\n\n")
		emitEnumConstants(b, typeName, schema.Enum)
	}
}

func hasUnion(doc ir.Document, names []string) bool {
	for _, name := range names {
		if doc.Schemas[name].Type == "union" {
			return true
		}
	}
	return false
}

func schemaRefGoType(ref ir.SchemaRef) string {
	return gotype.Ref(ref, exportedName)
}

func schemaGoType(schemaType string, items *ir.SchemaRef, format string) string {
	return gotype.Ref(ir.SchemaRef{Type: schemaType, Items: items, Format: format}, exportedName)
}

func emitEnumConstants(b *strings.Builder, typeName string, values []string) {
	if len(values) == 0 {
		return
	}
	b.WriteString("const (\n")
	for _, value := range values {
		b.WriteString("\t")
		b.WriteString(typeName)
		b.WriteString(exportedName(value))
		b.WriteString(" ")
		b.WriteString(typeName)
		b.WriteString(" = ")
		b.WriteString(quotedGoString(value))
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func exportedName(value string) string {
	parts := splitIdentifier(value)
	if len(parts) == 0 {
		return "Value"
	}
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func splitIdentifier(value string) []string {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}
	var words []string
	var current strings.Builder
	var prevLower bool
	for _, r := range value {
		if r == '-' || r == '_' || r == '.' || r == '/' || r == ' ' {
			if current.Len() > 0 {
				words = append(words, current.String())
				current.Reset()
			}
			prevLower = false
			continue
		}
		isUpper := 'A' <= r && r <= 'Z'
		if isUpper && prevLower && current.Len() > 0 {
			words = append(words, current.String())
			current.Reset()
		}
		current.WriteRune(r)
		prevLower = 'a' <= r && r <= 'z'
	}
	if current.Len() > 0 {
		words = append(words, current.String())
	}
	if len(words) == 0 {
		return nil
	}
	return words
}

func quotedGoString(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `\"`) + `"`
}
