// Package modelts emits TypeScript data-contract model types from APIGen IR.
package modelts

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Yacobolo/toolbelt/apigen/emit/contractutil"
	"github.com/Yacobolo/toolbelt/apigen/ir"
)

// Options configures TypeScript model emission.
type Options struct{}

// Emit renders TypeScript data-contract model types for doc.Contracts.
func Emit(doc ir.Document, _ Options) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by apigen data-contract TypeScript emitter. DO NOT EDIT.\n\n")
	b.WriteString("export type JsonObject = Record<string, unknown>\n\n")
	for _, name := range contractutil.DependencyNames(doc) {
		schema, ok := doc.Schemas[name]
		if !ok {
			return nil, fmt.Errorf("contract schema %q is missing", name)
		}
		emitSchema(&b, name, schema)
	}
	rootTypes := make([]string, 0, len(doc.Contracts))
	for _, contract := range doc.Contracts {
		rootTypes = append(rootTypes, tsType(contract.Schema))
	}
	sort.Strings(rootTypes)
	if len(rootTypes) > 0 {
		b.WriteString("export type DataContractEnvelope = ")
		b.WriteString(strings.Join(rootTypes, " | "))
		b.WriteString("\n")
	}
	return []byte(b.String()), nil
}

func emitSchema(b *strings.Builder, name string, schema ir.Schema) {
	switch schema.Type {
	case "union":
		variants := make([]string, 0, len(schema.OneOf))
		for _, variant := range schema.OneOf {
			variants = append(variants, tsType(variant))
		}
		b.WriteString("export type ")
		b.WriteString(exportedName(name))
		b.WriteString(" = ")
		b.WriteString(strings.Join(variants, " | "))
		b.WriteString("\n\n")
	case "object", "":
		b.WriteString("export interface ")
		b.WriteString(exportedName(name))
		if schema.Base != nil {
			b.WriteString(" extends ")
			b.WriteString(tsType(*schema.Base))
		}
		b.WriteString(" {\n")
		required := contractutil.RequiredSet(schema)
		for _, propertyName := range contractutil.OrderedProperties(schema) {
			property := schema.Properties[propertyName]
			optional := ""
			if _, ok := required[propertyName]; !ok {
				optional = "?"
			}
			b.WriteString("  ")
			b.WriteString(propertyName)
			b.WriteString(optional)
			b.WriteString(": ")
			b.WriteString(tsType(property.Schema))
			b.WriteString("\n")
		}
		b.WriteString("}\n\n")
	case "array":
		itemType := "unknown"
		if schema.Items != nil {
			itemType = tsType(*schema.Items)
		}
		b.WriteString("export type ")
		b.WriteString(exportedName(name))
		b.WriteString(" = ")
		b.WriteString(itemType)
		b.WriteString("[]\n\n")
	default:
		b.WriteString("export type ")
		b.WriteString(exportedName(name))
		b.WriteString(" = ")
		if len(schema.Enum) > 0 {
			values := make([]string, 0, len(schema.Enum))
			for _, value := range schema.Enum {
				values = append(values, quotedTSString(value))
			}
			b.WriteString(strings.Join(values, " | "))
		} else {
			b.WriteString(scalarTSType(schema.Type))
		}
		b.WriteString("\n\n")
	}
}

func tsType(ref ir.SchemaRef) string {
	if ref.Ref != "" {
		name, ok := ir.NormalizedSchemaRefName(ref)
		if ok {
			return exportedName(name)
		}
		return "unknown"
	}
	if ref.AdditionalProperties != nil {
		if ref.AdditionalProperties.Schema != nil {
			return "Record<string, " + tsType(*ref.AdditionalProperties.Schema) + ">"
		}
		return "JsonObject"
	}
	switch ref.Type {
	case "boolean":
		return "boolean"
	case "integer", "number":
		return "number"
	case "array":
		itemType := "unknown"
		if ref.Items != nil {
			itemType = tsType(*ref.Items)
		}
		return itemType + "[]"
	case "object":
		return "JsonObject"
	case "string":
		if len(ref.Enum) > 0 {
			values := make([]string, 0, len(ref.Enum))
			for _, value := range ref.Enum {
				values = append(values, quotedTSString(value))
			}
			return strings.Join(values, " | ")
		}
		return "string"
	default:
		return "unknown"
	}
}

func scalarTSType(schemaType string) string {
	switch schemaType {
	case "boolean":
		return "boolean"
	case "integer", "number":
		return "number"
	case "string":
		return "string"
	default:
		return "unknown"
	}
}

func exportedName(value string) string {
	parts := strings.FieldsFunc(strings.TrimSpace(value), func(r rune) bool {
		return r == '-' || r == '_' || r == '.' || r == '/' || r == ' '
	})
	if len(parts) == 0 {
		return "Value"
	}
	for i := range parts {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func quotedTSString(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "\\'") + "'"
}
